name: Lint Code Base
on: pull_request
jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: Install modules
        run: yarn
      - name: ESLint
        run: yarn run eslint . --ext .js,.json,.jsx,.tsx,.ts
